/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tom_codecanativewin_NativeWinCodec */

#ifndef _Included_com_tom_codecanativewin_NativeWinCodec
#define _Included_com_tom_codecanativewin_NativeWinCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tom_codecanativewin_NativeWinCodec
 * Method:    setAndplay
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_tom_codecanativewin_NativeWinCodec_setAndplay
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_tom_codecanativewin_NativeWinCodec
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tom_codecanativewin_NativeWinCodec_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
